[2023-10-07T06:26:24.180+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-10-07T06:26:24.187+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.transform_data scheduled__2023-10-07T01:00:00+00:00 [queued]>
[2023-10-07T06:26:24.198+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.transform_data scheduled__2023-10-07T01:00:00+00:00 [queued]>
[2023-10-07T06:26:24.199+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-07T06:26:24.210+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform_data> on 2023-10-07 01:00:00+00:00
[2023-10-07T06:26:24.232+0000] {standard_task_runner.py:57} INFO - Started process 607 to run task
[2023-10-07T06:26:24.241+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ETL', 'transform_data', 'scheduled__2023-10-07T01:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpupqoyqht']
[2023-10-07T06:26:24.241+0000] {standard_task_runner.py:85} INFO - Job 204: Subtask transform_data
[2023-10-07T06:26:24.253+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-07T06:26:24.292+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL.transform_data scheduled__2023-10-07T01:00:00+00:00 [running]> on host 16e40c1fcc3f
[2023-10-07T06:26:24.311+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-10-07T06:26:24.363+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-07T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-07T01:00:00+00:00'
[2023-10-07T06:26:25.970+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/help_function/ETL_Data.py", line 35, in transform_data
    os.remove(path_excel)
FileNotFoundError: [Errno 2] No such file or directory: 'data.xlsx'
[2023-10-07T06:26:25.976+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ETL, task_id=transform_data, execution_date=20231007T010000, start_date=20231007T062624, end_date=20231007T062625
[2023-10-07T06:26:25.986+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 204 for task transform_data ([Errno 2] No such file or directory: 'data.xlsx'; 607)
[2023-10-07T06:26:26.018+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-07T06:26:26.041+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
